apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cpanel-update-dns.fullname" . }}
  labels:
    app: {{ template "cpanel-update-dns.name" . }}
    chart: {{ template "cpanel-update-dns.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  username: {{ .Values.cpanel.username | b64enc }}
  password: {{ .Values.cpanel.password | b64enc }}
  url: {{ .Values.cpanel.url | b64enc }}
